In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time

In [ ]:
print(torch.__version__)

2.5.1+cu124


In [ ]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
scaler.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[3,4,5],[2,2,3]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 2, 3]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [2, 2, 3]])

In [ ]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.3256, 0.9385, 0.0990, 0.9770],
         [0.7345, 0.7361, 0.2768, 0.0450],
         [0.4516, 0.9749, 0.5807, 0.9540]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.rand(3,3)

tensor([[0.6416, 0.8373, 0.6303],
        [0.6081, 0.8510, 0.3322],
        [0.3665, 0.5842, 0.2659]])

In [ ]:
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype = None,device=None,requires_grad=False)
print(float_32_tensor)
float_32_tensor.dtype

tensor([3., 6., 9.])


torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor


tensor([ 9., 36., 81.])

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2393, 0.0849, 0.0916, 0.2647],
        [0.1975, 0.0311, 0.7260, 0.9523],
        [0.8614, 0.6115, 0.4549, 0.3277]])

In [ ]:
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


In [ ]:
# Tensor Operations

tensor = torch.tensor([1,2,3])
tensor + 10
tensor * 100
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)
torch.add (tensor,10)

tensor([11, 12, 13])

In [ ]:
# Matrix Multiplication

# 1. Element-Wise

tensor
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [ ]:

torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
# Rule 1: Inner Dimension of the matrix multiple should match
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.8869, 0.5389, 0.5692],
        [0.8823, 0.7242, 1.0353],
        [0.3558, 0.3188, 0.4842]])

In [ ]:
# Rule 2: The resultant matrix will be of outer dimension
torch.matmul(torch.rand(3,2) , torch.rand(2,3)).shape


torch.Size([3, 3])

In [ ]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
print(tensor_A.shape)
print(tensor_B.shape)
print(tensor_B.T.shape)
torch.matmul(tensor_A.T,tensor_B).shape

torch.Size([3, 2])
torch.Size([3, 2])
torch.Size([2, 3])


torch.Size([2, 2])

In [ ]:
# Finding min,max,mean,sum(Tensor Aggregation)
x = torch.arange(0,100,10)
x.dtype
torch.min(x), x.min()
torch.max(x), x.max()
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
torch.sum(x), x.sum()


(tensor(450), tensor(450))

In [ ]:
x
x.argmin()
x.argmax()

tensor(9)

In [ ]:
# Reshaping,Stacking, Squeezing and UnSqueezing Tensors

x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:,0] = 5
z ,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([9, 1])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
x_reshaped.unsqueeze(dim=0).shape

torch.Size([1, 9, 1])

In [ ]:
# Permute : Rearrange the Dimensions of the target Tensor
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [83]:
x[0][0]

tensor([1, 2, 3])

In [84]:
x[0][0][0]

tensor(1)

In [85]:
x[:,:,1]

tensor([[2, 5, 8]])

In [87]:
# PyTorch and NumPy
import torch
import numpy as np

arrary = np.arange(1.0,8.0)
tensor = torch.from_numpy(arrary).type(torch.float32)
arrary.dtype,tensor.dtype
arrary,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [88]:
arrary = arrary + 1
arrary,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [89]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [92]:
# Reproducibility
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)


print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [1]:
# Running Tensors on GPU

!nvidia-smi

Tue Feb 25 08:46:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   35C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
# Check for GPU in PyTorch
import torch
torch.cuda.is_available()

True

In [9]:
# Setup a device Agnostic Code
device = "cuda" if torch.cuda.is_available() else "cpu"
device
torch.cuda.device_count()

1

In [11]:
# Putting Tensor on GPU

tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [12]:
# Moving tensor back to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])