In [1]:
import torch
print(torch.__version__)

2.5.1+cu124


In [2]:
if torch.cuda.is_available():
    print("CUDA is available.")
    print("Number of CUDA devices:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available.")

CUDA is available.
Number of CUDA devices: Tesla T4


**Creating a Tensor**

In [4]:
# Using empty
a = torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.9275, 0.0459, 0.6475],
        [0.9928, 0.9206, 0.8860]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
print("using a range --->", torch.arange(0,10,2))

print("using linspace-->", torch.linspace(0,10,10))

print("using eye --> ", torch.eye(5))

print("using full -->", torch.full((3,3),5))

using a range ---> tensor([0, 2, 4, 6, 8])
using linspace--> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full --> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shape

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[    137284639726992,           152401168,                   0],
        [                  0,                   0, 7310593858020254331]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [26]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Type

In [19]:
x.dtype

torch.int64

In [20]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

1. Scaler Operations

In [28]:
x= torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [33]:
x + 2
x - 2
x * 3
x / 3
(x * 100)//3
((x * 100)//3)%2

tensor([[1., 1.],
        [1., 0.]])

# 2. Element Wise Operations

In [34]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)


tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])
tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])


In [36]:
a + b
a - b
a * b
a / b
a % b

tensor([[0.1784, 0.3346, 0.0706],
        [0.2767, 0.4440, 0.2063]])

In [40]:
c = torch.tensor([1,-2,3,-4])
torch.abs(c)
torch.neg(c)

tensor([-1,  2, -3,  4])

In [42]:
d = torch.tensor([1.9,2.3,3.4,4.3])
torch.round(d)
torch.floor(d)
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [43]:
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# 3. Reduction Operations

In [44]:
e = torch.randint(size=(2,3),low=0,high=10)
e

tensor([[0, 9, 5],
        [7, 3, 9]])

In [46]:
torch.sum(e)
torch.sum(e,dim=0)
torch.sum(e,dim=1)

tensor([14, 19])

In [47]:
torch.mean(e.float(),dim=0)

tensor([3.5000, 6.0000, 7.0000])

In [48]:
torch.median(e)

tensor(5)

In [49]:
torch.max(e)
torch.min(e)

tensor(0)

In [51]:
torch.std(e.float())

tensor(3.5637)

In [52]:
torch.argmax(e)

tensor(1)

# 4. Matrix Operations

In [53]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[4, 0, 5],
        [7, 5, 9]])
tensor([[9, 7],
        [5, 9],
        [8, 9]])


In [54]:
torch.matmul(f,g)

tensor([[ 76,  73],
        [160, 175]])

In [55]:
vector1=torch.tensor([1,2,3])
vector2=torch.tensor([4,5,6])
torch.dot(vector1,vector2)

tensor(32)

In [56]:
torch.transpose(f,0,1)

tensor([[4, 7],
        [0, 5],
        [5, 9]])

# 5. Comparision Operations

In [57]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[7, 9, 2],
        [6, 7, 7]])
tensor([[8, 3, 6],
        [1, 5, 5]])


In [59]:
i > j
i < j
i == j

tensor([[False, False, False],
        [False, False, False]])

In [60]:
k = torch.randint(size=(2,3),low=0,high=10)
print(k)

tensor([[0, 4, 3],
        [8, 8, 3]])


In [61]:
torch.log(k)

tensor([[  -inf, 1.3863, 1.0986],
        [2.0794, 2.0794, 1.0986]])

In [62]:
torch.sqrt(k)

tensor([[0.0000, 2.0000, 1.7321],
        [2.8284, 2.8284, 1.7321]])

In [63]:
torch.sigmoid(k)

tensor([[0.5000, 0.9820, 0.9526],
        [0.9997, 0.9997, 0.9526]])

In [66]:
torch.softmax(k.float(),dim=0)

tensor([[3.3535e-04, 1.7986e-02, 5.0000e-01],
        [9.9966e-01, 9.8201e-01, 5.0000e-01]])

In [67]:
torch.relu(k.float())

tensor([[0., 4., 3.],
        [8., 8., 3.]])

# Inplace Operations

In [68]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.3379, 0.2170, 0.9454],
        [0.7116, 0.1157, 0.6574]])
tensor([[0.3451, 0.0453, 0.9798],
        [0.5548, 0.6868, 0.4920]])


In [69]:
m + n

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

In [70]:
m.add_(n)

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

In [71]:
m

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

In [72]:
m.relu_()

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

In [73]:
m

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

# Copying a Tensor

In [74]:
a = torch.rand(2,3)
a

tensor([[0.0748, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [75]:
b = a
b

tensor([[0.0748, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [76]:
a[0][0]= 0

In [77]:
b

tensor([[0.0000, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [78]:
id(a)

137279727701936

In [79]:
id(b)

137279727701936

In [81]:
b = a.clone()
b

tensor([[0.0000, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [83]:
a[0][0] = 10
a

tensor([[10.0000,  0.9605,  0.3271],
        [ 0.0103,  0.9516,  0.2855]])

In [84]:
b

tensor([[0.0000, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

# Tensor Operations on GPU

In [85]:
torch.cuda.is_available()

True

In [86]:
device = torch.device('cuda')

In [87]:
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [88]:
a = torch.rand(2,3)

In [91]:
b= a.to(device)
b + 5

tensor([[5.2324, 5.9141, 5.7668],
        [5.1659, 5.4393, 5.2243]], device='cuda:0')

# Difference Between GCP and CPU

In [93]:
import time

size = 10000

matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size,size)

start_time = time.time()
result_cpu = torch.mm(matrix_cpu1,matrix_cpu2)
end_time = time.time()

print("CPU Time:", end_time - start_time)

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# Measure time on GPU
start_time_gpu = time.time()
result_gpu = torch.mm(matrix_gpu1, matrix_gpu2)
end_time_gpu = time.time()

print("GPU Time:", end_time_gpu - start_time_gpu)
# Compare results
print("CPU Result:", result_cpu)
print("GPU Result:", result_gpu)


CPU Time: 18.214244604110718
GPU Time: 0.012862205505371094
CPU Result: tensor([[2503.5139, 2500.8469, 2511.3894,  ..., 2495.6399, 2509.4795,
         2495.6240],
        [2488.1318, 2513.6084, 2508.6616,  ..., 2506.0132, 2509.0264,
         2482.8477],
        [2490.4661, 2502.9270, 2497.3391,  ..., 2504.8740, 2513.4248,
         2489.3958],
        ...,
        [2517.8594, 2497.0125, 2508.7952,  ..., 2506.6306, 2518.1785,
         2504.4927],
        [2518.1353, 2563.0789, 2541.9482,  ..., 2549.4521, 2554.4150,
         2541.9602],
        [2518.5620, 2537.4807, 2531.1555,  ..., 2534.3381, 2524.6868,
         2507.5249]])
GPU Result: tensor([[2503.5144, 2500.8459, 2511.3857,  ..., 2495.6406, 2509.4785,
         2495.6289],
        [2488.1331, 2513.6096, 2508.6633,  ..., 2506.0139, 2509.0271,
         2482.8469],
        [2490.4692, 2502.9285, 2497.3416,  ..., 2504.8792, 2513.4231,
         2489.3970],
        ...,
        [2517.8494, 2497.0107, 2508.7937,  ..., 2506.6294, 2518.1807,


# Tensor Reshape

In [94]:
a = torch.rand(4,4)
a

tensor([[0.2147, 0.8954, 0.0273, 0.6760],
        [0.8880, 0.2082, 0.1337, 0.6727],
        [0.1681, 0.0738, 0.1151, 0.0083],
        [0.0504, 0.1486, 0.8395, 0.8331]])

In [95]:
a.reshape(2,2,2,2)

tensor([[[[0.2147, 0.8954],
          [0.0273, 0.6760]],

         [[0.8880, 0.2082],
          [0.1337, 0.6727]]],


        [[[0.1681, 0.0738],
          [0.1151, 0.0083]],

         [[0.0504, 0.1486],
          [0.8395, 0.8331]]]])

In [96]:
a.flatten()


tensor([0.2147, 0.8954, 0.0273, 0.6760, 0.8880, 0.2082, 0.1337, 0.6727, 0.1681,
        0.0738, 0.1151, 0.0083, 0.0504, 0.1486, 0.8395, 0.8331])

In [97]:
b = torch.rand(2,3,4)
b

tensor([[[0.4379, 0.4083, 0.5009, 0.4067],
         [0.9891, 0.1025, 0.9936, 0.3642],
         [0.8499, 0.3817, 0.2436, 0.1008]],

        [[0.1176, 0.3651, 0.4549, 0.8776],
         [0.3721, 0.7827, 0.4926, 0.7323],
         [0.4682, 0.4369, 0.3151, 0.6987]]])

In [99]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [100]:
c = torch.rand(226,226,3)

In [101]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

# NumPy and PyTorch

In [102]:
import numpy as np

In [103]:
 a = torch. tensor([1,2,3])
 a

tensor([1, 2, 3])

In [105]:
b = a.numpy()
type(b)

numpy.ndarray

In [106]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [107]:
torch.from_numpy(c)

tensor([1, 2, 3])