In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0    842302         M        17.99  ...          0.4601                  0.11890          NaN
1    842517         M        20.57  ...          0.2750                  0.08902          NaN
2  84300903         M        19.69  ...          0.3613                  0.08758          NaN
3  84348301         M        11.42  ...          0.6638                  0.17300          NaN
4  84358402         M        20.29  ...          0.2364                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [6]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[-0.77270917, -1.34910016, -0.74619877, ..., -0.3954001 ,
        -1.2445187 , -0.87123311],
       [ 0.40648218,  0.06088328,  0.42798248, ...,  0.5912028 ,
        -0.09557444, -0.201824  ],
       [-0.21132381, -0.50866668, -0.27366241, ..., -0.2341648 ,
        -0.61299015, -0.41646854],
       ...,
       [-0.0335988 ,  0.00531743, -0.10264926, ..., -0.46506222,
        -0.84746857, -0.42730918],
       [ 0.26825162, -0.52487339,  0.20378341, ..., -0.41444007,
        -0.77243548, -1.06419638],
       [-0.14361905, -0.0757161 , -0.12842397, ...,  0.49902517,
        -0.36287984, -0.38232055]])

In [11]:
y_train

139    B
131    M
224    B
465    B
19     B
      ..
557    B
501    M
481    B
169    B
396    B
Name: diagnosis, Length: 455, dtype: object

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
X_train_tensor

tensor([[-0.7727, -1.3491, -0.7462,  ..., -0.3954, -1.2445, -0.8712],
        [ 0.4065,  0.0609,  0.4280,  ...,  0.5912, -0.0956, -0.2018],
        [-0.2113, -0.5087, -0.2737,  ..., -0.2342, -0.6130, -0.4165],
        ...,
        [-0.0336,  0.0053, -0.1026,  ..., -0.4651, -0.8475, -0.4273],
        [ 0.2683, -0.5249,  0.2038,  ..., -0.4144, -0.7724, -1.0642],
        [-0.1436, -0.0757, -0.1284,  ...,  0.4990, -0.3629, -0.3823]],
       dtype=torch.float64)

# Building the Model

In [28]:
class MySimpleNN():

  def __init__(self,X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


In [30]:
learning_rate = 0.1
epochs = 25

In [31]:
# Create Model

model = MySimpleNN(X_train_tensor)

# Define Loop
for epoch in range (epochs):

  # Forward Pass
  y_pred = model.forward(X_train_tensor)
  #print(y_pred)

  # Loss Calculate
  loss = model.loss_function(y_pred, y_train_tensor)
  #print(loss)

  # Backward Pass
  loss.backward()

  # Parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # Zero Gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

  # Print Loss in each epoch
    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 4.365544444230523
Epoch: 2, Loss: 4.285761192602311
Epoch: 3, Loss: 4.19875309525459
Epoch: 4, Loss: 4.105953128865704
Epoch: 5, Loss: 4.007287703132923
Epoch: 6, Loss: 3.9019929812499536
Epoch: 7, Loss: 3.790139951854935
Epoch: 8, Loss: 3.67567878746336
Epoch: 9, Loss: 3.5589638720326455
Epoch: 10, Loss: 3.4377115697192004
Epoch: 11, Loss: 3.312516400949484
Epoch: 12, Loss: 3.1841008531154995
Epoch: 13, Loss: 3.0543610627225397
Epoch: 14, Loss: 2.920870409705064
Epoch: 15, Loss: 2.782018078994833
Epoch: 16, Loss: 2.6345046914719794
Epoch: 17, Loss: 2.485048154054361
Epoch: 18, Loss: 2.3339334774574767
Epoch: 19, Loss: 2.180321387671351
Epoch: 20, Loss: 2.025340864405739
Epoch: 21, Loss: 1.8710576441939442
Epoch: 22, Loss: 1.724839045877427
Epoch: 23, Loss: 1.5828527751326273
Epoch: 24, Loss: 1.448333360535433
Epoch: 25, Loss: 1.3265023514302319


In [32]:
model.weights

tensor([[-0.2212],
        [ 0.6116],
        [-0.3415],
        [-0.1374],
        [ 0.3395],
        [-0.0780],
        [ 0.2811],
        [-0.1367],
        [ 0.4836],
        [ 0.2404],
        [ 0.2635],
        [ 0.5555],
        [-0.0591],
        [-0.3358],
        [ 0.2583],
        [-0.3586],
        [ 0.3474],
        [ 0.3550],
        [ 0.5186],
        [ 0.3942],
        [ 0.4327],
        [-0.2667],
        [ 0.4284],
        [ 0.4498],
        [ 0.3349],
        [-0.4538],
        [ 0.1254],
        [ 0.1412],
        [ 0.2732],
        [ 0.1299]], dtype=torch.float64, requires_grad=True)

In [33]:
model.bias

tensor([-0.1052], dtype=torch.float64, requires_grad=True)

In [35]:
# Model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5467836260795593
